package com.dreambig.app4it.enums;

public enum NewsType {
	
	INVITED_TO_ACTIVITY,
	ACTIVITY_CANCELLED,
	NEW_COMMENT,
	NEW_WHEN_SUGGESTION,
	NEW_WHERE_SUGGESTION,
	ACTIVITY_TITLE_EDITED,
	ACTIVITY_DESCRIPTION_EDITED,
	ACTIVITY_TIME_EDITED,
	ACTIVITY_PLACE_EDITED,
	ACTIVITY_TYPE_EDITED

}
